--- 
log_file: log/mongrel.log
cwd: /var/www/apps/thoughtlead/current/
port: "8000"
environment: staging
address: 127.0.0.1
pid_file: tmp/pids/mongrel.pid
servers: 2
docroot: public
user: verticality
group: verticality